# fly.toml app configuration file generated for ws-gateway on 2023-08-15T19:30:52+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ws-gateway"
primary_region = "ams"

[build]
# Buildpack is disabled until they support go1.21
# builder = "paketobuildpacks/builder:base"
# buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
PORT = "8080"
[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[checks]
[checks.http]
grace_period = "30s"
interval = "15s"
method = "get"
path = "/up"
port = 8080
timeout = "10s"
type = "http"

[metrics]
port = 9090
path = "/metrics"
